(package "typescript-mode"
         "0.4"
         "Major mode for editing typescript")

(website-url "http://github.com/ananthakumaran/typescript.el")
(keywords "typescript" "languages")

(package-file "typescript-mode.el")

(files "*.el")

(source "gnu")
(source "melpa")

(depends-on "emacs" "24.3")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
