(package "typescript-mode"
         "0.4"
         "Major mode for editing typescript")

(package-file "typescript-mode.el")

(files
  "typescript-mode.el"
  "typescript-mode-general-tests.el"
  "typescript-mode-jsdoc-tests.el"
  "typescript-mode-lexical-binding-tests.el"
  "typescript-mode-tests.el"
  "typescript-mode-test-utilities.el"
  ;; "typescript-tree-sitter.el"
  ;; "typescript-ts.el"
  )


(source "gnu")
(source "melpa")

(depends-on "emacs" "24.3")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
